foreground              #352B2D
background              #F1DBC2
selection_foreground    #F1DBC2
selection_background    #4B3D43
cursor                  #352B2D
cursor_text_color       #F1DBC2
url_color               #4B3D43
active_border_color     #4B3D43
inactive_border_color   #CCB7A0
bell_border_color       #44373A
active_tab_foreground   #F1DBC2
active_tab_background   #4B3D43
inactive_tab_foreground #44373A
inactive_tab_background #DFC8B1
tab_bar_background      #F1DBC2
color0  #625458
color1  #4B3D43
color2  #625458
color3  #44373A
color4  #625458
color5  #857974
color6  #625458
color7  #352B2D
color8  #44373A
color9  #352B2D
color10 #4B3D43
color11 #352B2D
color12 #625458
color13 #44373A
color14 #44373A
color15 #352B2D
