foreground              #F1DBC2
background              #352B2D
selection_foreground    #352B2D
selection_background    #CCB7A0
cursor                  #F1DBC2
cursor_text_color       #352B2D
url_color               #CCB7A0
active_border_color     #CCB7A0
inactive_border_color   #4B3D43
bell_border_color       #DFC8B1
active_tab_foreground   #352B2D
active_tab_background   #CCB7A0
inactive_tab_foreground #DFC8B1
inactive_tab_background #44373A
tab_bar_background      #352B2D
color0  #AA9D8A
color1  #CCB7A0
color2  #AA9D8A
color3  #DFC8B1
color4  #DFC8B1
color5  #908A7B
color6  #DFC8B1
color7  #F1DBC2
color8  #AA9D8A
color9  #F1DBC2
color10 #CCB7A0
color11 #F1DBC2
color12 #AA9D8A
color13 #DFC8B1
color14 #F1DBC2
color15 #F1DBC2
